### ISSUE TITLE
404

### ISSUE THREAD

**Issue by sigmarsson** [PrismLibrary/Prism-Documentation#103]
The demo project not found. 

https://github.com/unoplatform/Uno.Prism/tree/master/Sandbox/Uno/HelloWorld

**Comment by brianlagunas** [comment]
where did you find this link? Can you submit a PR that fixes it?

**Comment by sigmarsson** [comment]
@brianlagunas 

Just clicked on the link: 

![image](https://user-images.githubusercontent.com/43340959/126199571-63eda21f-0f81-4a63-a4fb-8838d10d24a9.png)

https://github.com/unoplatform/Uno.Prism/

**Comment by brianlagunas** [comment]
That's not the Prism repo. We do not control that content.
