### ISSUE TITLE
Xamarin.Forms Working with NavigationPages is empty

### ISSUE THREAD

**Issue by Countryen** [PrismLibrary/Prism-Documentation#105]
The page that documents how to work with **NavigationPages** is empty, only headers are inside.
https://prismlibrary.com/docs/xamarin-forms/navigation/working-with-navigationpages.html

Maybe this was moved but where are information about this topic?
`_navigationService.NavigateAsync("NavigationPage/MainPage");`

There are information about this on https://prismlibrary.com/docs/xamarin-forms/navigation/working-with-masterdetailpages.html But this page focuses on MasterDetailPages not NavigationPages - or is that all available/needed?

If so could you remove the first page and just refer to the other page? Looks like a big gap currently.

**Comment by Countryen** [comment]
I've seen there is a PR #31 in progress, but for a long time.

**Comment by brianlagunas** [comment]
We are aware that this page is empty and needs content. It'll get done one day :)
