### ISSUE TITLE
Prism Template Pack stopped working after installing a few other vsix

### ISSUE THREAD

**Issue by hcalxhcalxhcalx** [PrismLibrary/Prism-Documentation#111]
I had installed PrismTemplatePack.vsix few month ago and it worked fine.
Over the past 2-3 weeks I also installed:
ProjectReunion.Extension.vsix
OpenSilver-1.0.0-alpha-007.vsix
SQLite_and_SQL_Server_Compact_Toolbox_v4.7.691.vsix
Now, when I create a new solution of type "Blank App (WPF) (Brian Lagunas)" - it adds all solution/project files, but doesn't write project entry in .sln file. Solution Explorer shows 0 projects.
Reinstalling PrismTemplatePack.vsix didn't help.
VS2019 16.9.4

**Comment by brianlagunas** [comment]
Prism is not responsible for any conflicts with other extensions. Which there should be no conflicts because it's just project templates. The Prism template pack doesn't use any shared assemblies. Unless VS broke something in an update.
