### ISSUE TITLE
Additional topics?

### ISSUE THREAD

**Issue by MichaelPonti** [PrismLibrary/Prism-Documentation#113]
Hi @brianlagunas , things have been kind of crazy for me at work the last few months, but I might have some more time to help out with the docs, especially over the next couple of weeks. I think all of the wpf stuff has been brought up to date, but if there is something missing, or needs more work, I will try and get it done.

**Comment by brianlagunas** [comment]
Things have been crazy for me too. The WPF docs look great. You really helped us out a ton. Nothing stands out to me right now, but if something comes up, I'll be sure to create an issue that you can grab if you like. Thanks again!

**Comment by MichaelPonti** [comment]
Sounds good, am glad I could help out :)
