### ISSUE TITLE
Prism with MAUI 

### ISSUE THREAD

**Issue by Sofiya-kumar** [PrismLibrary/Prism-Documentation#123]
Hi, 

I would like to have both modal and non-modal page navigation.

But modal navigation not working as expected I navigated to a new page with the below example.

<img width="483" alt="image" src="https://user-images.githubusercontent.com/130461522/231368402-c3a9347b-3d94-4070-ab21-3f2e01eafd6e.png">

**Comment by brianlagunas** [comment]
This is not the correct repo to report issues in Prism. This is the documentation repo. Please report this in the appropriate repo and be sure to search for existing issues first.
