### ISSUE TITLE
MAUI Documentation appears to be Out-of-Date

### ISSUE THREAD

**Issue by askariya** [PrismLibrary/Prism-Documentation#127]
I noticed that shortly before it was archived and merged into the Prism project, the Prism.MAUI project had the ReadMe (https://github.com/PrismLibrary/Prism.Maui) updated to change the instructions from using `UsePrismApp<App>()` to `UsePrism()` in MauiProgram.cs. 

However, the docs in this repo still seem to reflect the older method of using `UsePrismApp<App>`. 
Are the docs out-of-date, or is this just because Prism.MAUI is still in pre-release? Am I looking in the wrong place?

**Comment by dansiegel** [comment]
docs are the last thing to get updated. They are actually more up to date in this repo than on the docs site as our CI is currently broken. Generally the docs are the last thing to get done

**Comment by askariya** [comment]
> docs are the last thing to get updated. They are actually more up to date in this repo than on the docs site as our CI is currently broken. Generally the docs are the last thing to get done

Good to know, thanks! Do you know where I can track progress and/or see updates other than in the repositories themselves?
Just want to get an idea of when the MAUI implementation will be ready to use.

**Comment by sujeetulli** [comment]
Any updates on this.

**Comment by dansiegel** [comment]
You can follow the pending issues in the [Prism 9.0 milestone](https://github.com/PrismLibrary/Prism/milestone/17). The docs just got a publish pipeline last night and should be public hopefully later today or tomorrow.
