### ISSUE TITLE
Namespacing/Using statements in examples?

### ISSUE THREAD

**Issue by p0lar-bear** [PrismLibrary/Prism-Documentation#2]
I'm brand new to Prism and coming in with just enough hands-on experience with WPF to be dangerous, so that may be the root of the issue.

But, the docs are confusing for me to follow on their own - in the WPF Initializing chapter alone it's entirely ambiguous to me which classes are being used in examples for return types and the like. I think that it should be clarified via namespacing, or the inclusion of `using` statements, exactly which classes are being used.

i.e. instead of this example on the WPF Initializing chapter:

    protected override DependencyObject CreateShell()
    {
        return ServiceLocator.Current.GetInstance<Shell>();
    }

I think it should read either:

    using System.Windows;
    using CommonServiceLocator;
    using YourApp.Views;

    protected override DependencyObject CreateShell()
    {
        return ServiceLocator.Current.GetInstance<Shell>();
    }

or:

    protected override System.Windows.DependencyObject CreateShell()
    {
        return CommonServiceLocator.ServiceLocator.Current.GetInstance<YourApp.Views.Shell>();
    }

**Comment by brianlagunas** [comment]
Thanks for the feedback.  Actually, what's more important is that if you found a sample that is showing that code snippet, it needs to be fixed.  You should never be calling `ServiceLocator.Current.GetInstance<Shell>();'

If you like, you can submit a PR. I would prefer the second example to use.

```
protected override System.Windows.DependencyObject CreateShell()
{
    return Container.Resolve<YourApp.Views.Shell>();
}
```

**Comment by p0lar-bear** [comment]
Thank you for the clarification. I don't think I'm the person for the job to do PRs on my own, though - I really don't know what's what in this framework.

**Comment by brianlagunas** [comment]
I just provided the snippet to use.  Just submit a PR to update the snippet.  This is not something I will be spending time doing.  So if you want it, best to do it while you're thinking about it.

**Comment by p0lar-bear** [comment]
Ah, alright, I can do that. I was thinking of the bigger picture.

**Comment by brianlagunas** [comment]
Yeah. It's a great suggestion, but honestly doing this across all docs is not something I really have time for.  While it makes it more clear, the current docs do work :).  So it's best to just update them as you come across the confusing parts.
