### ISSUE TITLE
Image in Xamarin.Forms/Application Lifecycle does not load

### ISSUE THREAD

**Issue by StraysWonderland** [PrismLibrary/Prism-Documentation#20]
Image for "how to activate debug-location" at the bottom of the page ["Xamarin.Forms/Application-Lifecycle"](https://github.com/PrismLibrary/Prism-Documentation/blob/master/docs/xamarin-forms/application-lifecycle.md/#L1) does not load.

![image](https://user-images.githubusercontent.com/22505258/49809470-453ac500-fd5f-11e8-856d-14911f71db7b.png)

( It does load when opening the markdown file, but not when visiting the website )

**Comment by brianlagunas** [comment]
Fixed! Should be live in about 20 minutes after the build has completed. Thanks for reporting this.
