### ISSUE TITLE
Remove link to old MS Docs

### ISSUE THREAD

**Issue by dansiegel** [PrismLibrary/Prism-Documentation#26]
We currently have a link in the WPF docs that links to a QuickStart sample in the old Microsoft Docs that is no longer a good sample... This should be updated to reflect the samples we have on GitHub.

http://prismlibrary.github.io/docs/wpf/Composing-the-UI.html#commands-ui-triggers-actions-and-behaviors

**Comment by brianlagunas** [comment]
I'm not spending any time on the legacy WPF docs. I will be rewriting them to greatly simplify the WPF docs and bring them to the current API.
