### ISSUE TITLE
Wrong image path in document

### ISSUE THREAD

**Issue by ghost** [PrismLibrary/Prism-Documentation#30]
In the following link, images reference to a path that doesn't exist.
actually you didn't move the image folder to new path
https://prismlibrary.github.io/docs/wpf/legacy/Introduction.html

for instance the first image refers to https://prismlibrary.github.io/docs/wpf/legacy/images/Ch1IntroFig1.png
and the result is 404 
while if you remove` /legacy `from the path, the image is there...

**Comment by brianlagunas** [comment]
Did you look at the code? Yes, the images are where they are supposed to be.

https://github.com/PrismLibrary/Prism-Documentation/blob/master/docs/wpf/legacy/images/Ch1IntroFig1.png
