### ISSUE TITLE
Conflicting .dlls with Unity.Abstractions

### ISSUE THREAD

**Issue by Glenn70** [PrismLibrary/Prism-Documentation#33]
1.  As best I can tell I need Prism.Unity in order to use the PrismApplication class.
2. Prism.Unity 7.1.0.431 needs Unity.Abstractions 3.3.1. It will not accept Unity.Abstractions 4.1.0.0, the current version, which other dlls in my solution require.
3. What should I do>

**Comment by brianlagunas** [comment]
don't upgrade Unity separately. It breaks binary compatibility.
