### ISSUE TITLE
Navigating between tabs destroys and instantiates a new instance of ViewModel

### ISSUE THREAD

**Issue by lestersconyers** [PrismLibrary/Prism-Documentation#44]
Hi guys. I have an app with tabbed pages. When the user switches over to PageA tab I load a large amount of data in PageAViewModel. When I navigate to MainPage/PageB PageAViewModel get reinstantiated and I lose that data I loaded. I thought that PageAViewModel would remain just as if a user is switching tabs using the tab control. I'm using:

`await NavigationService.NavigateAsync("MainPage?selectedTab=PageB", navParams);`

Is this expected behavior?

**Comment by brianlagunas** [comment]
Questions belong on StackOverflow, or Slack if you're a patron. Be sure to provide more information than what's in this issue so others can help you. I can tell you you're doing something wrong 😄

**Comment by lestersconyers** [comment]
Ok, ok. my bad :)
