### ISSUE TITLE
Xamarin Partial Views 

### ISSUE THREAD

**Issue by MikeEsteves** [PrismLibrary/Prism-Documentation#45]
I'd like to add a document explaining partial views with a code example of the parent and the partial view. Also some notes on when INavigatedAware methods are called for partial views and that using the IEventAggregator is a good solution to updating the view if changes happen in the parent.

Is there anything I should or shouldn't include?

**Comment by dansiegel** [comment]
That sounds good. The key note would be dynamically adding/removing Partial Views is unsupported. I would say start with a PR we can review and give further guidance from there.

**Comment by dansiegel** [comment]
Closing as Partial Views will be removed in favor of Regions in Prism 8
