### ISSUE TITLE
Update Xamarin Forms Passing-parameters documents

### ISSUE THREAD

**Issue by UnreachableCode** [PrismLibrary/Prism-Documentation#49]
The documents still talk about [INavigatingAware](https://prismlibrary.github.io/docs/xamarin-forms/navigation/passing-parameters.html#getting-parameters) in the _Getting parameters_ section. 

But as of Prism 7.2, INavigatingAware is obsolete and has been replaced with IInitialize. Can I update the docs to incorporate the usage defined [here](https://github.com/PrismLibrary/Prism/issues/1748)? 

And, maybe this is a separate issue, but would it be possible to show the latest version of Prism a document refers to, like the framework version which shows on Microsoft docs for example? #

**Comment by brianlagunas** [comment]
Yes, that would be great if you could help us update our docs.  We do not have a way to specify which version a particular topic belongs to. It is always assumed the docs always apply tot he latest released code.

**Comment by brianlagunas** [comment]
this has been fixed
