### ISSUE TITLE
Getting Started Topic

### ISSUE THREAD

**Issue by MichaelPonti** [PrismLibrary/Prism-Documentation#54]
@brianlagunas , I think I am going to have a bit of time over the next couple of weeks. If you aren't already working this topic, I will take a run at it. I remember seeing an issue somewhere where someone wanted guidance on converting from 6.x to 7, I can add that as a topic as well.

**Comment by brianlagunas** [comment]
That would be awesome!  Do what you can, and we will go from there.  Thank you so much.
