### ISSUE TITLE
All the WPF documentation is blank

### ISSUE THREAD

**Issue by hustmandotcom** [PrismLibrary/Prism-Documentation#57]
It looks like all the WPF documentation is missing, any chance of adding it back?
example - https://prismlibrary.com/docs/wpf/region-navigation/passing-parameters.html

**Comment by AlexHedley** [comment]
See the [Legacy](https://prismlibrary.com/docs/wpf/legacy/Introduction.html) section for the previous docs.

The last commits from the 10th Dec (#e0c39e4) were made to flesh out the new topics to be covered, see the Twitch streams from @brianlagunas:

- https://www.twitch.tv/videos/519665744
- https://www.twitch.tv/videos/520525798
