### ISSUE TITLE
Named services documentation deviates from actual behavior

### ISSUE THREAD

**Issue by less0** [PrismLibrary/Prism-Documentation#58]
According to the documentation ([Xamarin.Forms&nbsp;/&nbsp;Dependency&nbsp;Injection&nbsp;/&nbsp;Registering&nbsp;Types](https://prismlibrary.com/docs/xamarin-forms/dependency-injection/registering-types.html#understanding-named-services)) it should be possible to register a named service as 

```csharp
containerRegistry.Register<IService, Service>("fooService");
```

and consume it in a viewmodel by adding a parameter that's named similar to the registered service.

```csharp
public MainPageViewModel(IService fooService)
{
    // ...
}
```

However, when I'm trying to navigate to `MainPage` it fails with an exception that there is no public constructor for `IService` (which seems to me as if it tries to resolve an unnamed service and ignores the named services). It works when I'm registering the service with

```csharp
containerRegistry.Register<IService, Service>();
```

The behavior is the same when registering instances/singletons instead of transients. Furthermore the behavior seems to be invariant against the IoC container in use.

I don't know if this is an issue with the documentation or with the library itself, (actually the behavior is a non-issue for me, since with Unity I can still use `Unity.DependencyAttribute`), but it occurred to me that there seems to be a mismatch between the documentation and the actual behavior.

**Comment by dansiegel** [comment]
I believe this should be fixed.
