### ISSUE TITLE
Confusion with defining Detail page in xaml for MasterDetailPage

### ISSUE THREAD

**Issue by HelenMamalaki** [PrismLibrary/Prism-Documentation#63]
[https://prismlibrary.com/docs/xamarin-forms/navigation/working-with-masterdetailpages.html](https://prismlibrary.com/docs/xamarin-forms/navigation/working-with-masterdetailpages.html)

The link above on how to use Prism with Master Detail Pages currently says **'TBD'**. It would be useful to add how to use it, particularly on how a Detail page cannot be defined in XAML but only as part of Navigation MasterDetailPage/DetailPage. The Prism sample for Master detail page is empty too. https://github.com/PrismLibrary/Prism-Samples-Forms/tree/master/09-MasterDetail

When using Prism for TabbedPage (if I'm not mistaken) you can define the Tab Page in xaml, following from this I am in a situation when I want to define a <tabPage: MasterDetailPage /> as a Tab page - it will always fail to load as I am not able to "hardcode" the detail page in advance. This confusion is more for Stackoverflow but was wondering if there is a way to define Details page in advance, if not, would be nice to make clear in documentation.

**Comment by dpuckett** [comment]
Yes, please do write the docs for Master Detail page with Prism!
I'm having an issue where the NavigationService simply doesn't seem to want to navigate to a detail page on App Initialize.

`protected override async void OnInitialized()
{
    InitialiseComponent();
    await NavigationService.NavigateAsync("MainMasterDetailPage/NavigationPage/NewsPage");
}`

This does nothing and loads a completely blank screen.

But adding in x:Arguments with the page into the <MasterPage.Detail> node loads the page fine.

Obviously this means it's not using the NavigationService to load the NewsPage and so means I'm unable to take advantage of any navigation niceties like properties etc

My personal assumption is I've done something wrong, BUT without the docs I can't know that.

**Comment by dansiegel** [comment]
this is now resolved. 

https://prismlibrary.com/docs/xamarin-forms/navigation/working-with-masterdetailpages.html
