### ISSUE TITLE
wpf view composition edits

### ISSUE THREAD

**Issue by MichaelPonti** [PrismLibrary/Prism-Documentation#66]
Hi @brianlagunas , I am starting to do some work on the view-composition topic and using the legacy part as a base. In reading it, it contains a ton of information about things like MVVM, commands, user interactions, data binding, unit and ui testing.

I feel like it would be good to remove this stuff, or, have a list of topics that the user should be familiar with before attempting to use view composition. What is your preference?

**Comment by brianlagunas** [comment]
We should keep the focus on just the View Composition topic. Drop everything that doesn't apply.

**Comment by MichaelPonti** [comment]
Looks like I forgot to link this to the PR itself, going to close as it was completed.
