### ISSUE TITLE
Switch Prism-Documentation to german language

### ISSUE THREAD

**Issue by Ghislain1** [PrismLibrary/Prism-Documentation#7]
There is any option to get this documentation in german language ?

**Comment by brianlagunas** [comment]
If someone want to translate it and submit a PR.

**Comment by StraysWonderland** [comment]
I would like to translate it to german.
Just a quick question; how should it be done? any preference? Just create a folder and dump all markdown files in german into it ( as is done in #1 ) ?

**Comment by brianlagunas** [comment]
Yes, just create a new folder and start your work there.  Also, please only do the XamarinForms topics that have been completed.
