### ISSUE TITLE
[Bug] GTK# - Method add_ModuleDownloadProgressChanged does not have an implementation.

### ISSUE THREAD

**Issue by DlbSt** [PrismLibrary/Prism-Documentation#77]
### Description

I created GTK# project following the [documentation](https://prismlibrary.com/docs/xamarin-forms/platform-reference/gtk.html) and the application is crashing ("System.TypeLoadException: 'Method 'add_ModuleDownloadProgressChanged' in type 'Prism.Modularity.ModuleManager' from assembly 'Prism.Forms, Version=7.2.0.1422, Culture=neutral, PublicKeyToken=null' does not have an implementation."). I also followed the instructions of this [article](https://duanenewman.net/blog/post/using-prism-with-xamarin-forms-and-gtk/), but I was not able to reproduce the steps from article, because my csproj looks different.

### Steps to Reproduce

1. Clone the repo included in reproduction link and start PrismGTKTest.GTK project.

### Expected Behavior
Program does not crash and display the simple GUI.

### Actual Behavior
Program crashes -> "System.TypeLoadException: 'Method 'add_ModuleDownloadProgressChanged' in type 'Prism.Modularity.ModuleManager' from assembly 'Prism.Forms, Version=7.2.0.1422, Culture=neutral, PublicKeyToken=null' does not have an implementation."

### Basic Information

- Version with issue: 7.2.0.1422 & 7.2.0.1367 (earlier versions are missing Prism.Navigation) 
- Last known good version: -
- Xamarin.Forms version: 4.8.0.1269
- IDE: Visual Studio 2019 (16.7.0) - Win 10

### Screenshots

**Exception:**
![image](https://user-images.githubusercontent.com/51118738/89785246-621e3180-db1a-11ea-9edd-002ede16212e.png)

**CsProj**
![image](https://user-images.githubusercontent.com/51118738/89785986-80d0f800-db1b-11ea-9a36-2fda3023b6f8.png)

### Reproduction Link

[https://github.com/DlbSt/PrismGTKTest](https://github.com/DlbSt/PrismGTKTest)

**Comment by dansiegel** [comment]
@DlbSt your issue is with documentation, I have transferred this to the appropriate repo. Feel free to provide a PR to update the docs if they need some updating for working with GTK.

**Comment by DlbSt** [comment]
@dansiegel I am happy to help here, unfortunately I found the code [here](https://duanenewman.net/blog/post/a-better-way-to-override-references-with-packagereference/) (and this would be my first PR), so I don't know if I wouldn't have problem with license or copyright in this case.

**Comment by dansiegel** [comment]
@DlbSt there's no copyright issue... @duanenewman created the docs for GTK along with writing the article, if something is out of date you're free to make the update and send a PR

**Comment by duanenewman** [comment]
@DlbSt Feel free to use those bits in an update to the docs. I think the demo code doesn't have it because of an update to newer PrismLib doesn't require it and I missed the update in the sample.. I think what I was doing in that blog post isn't needed if PrismLib is updated (I may be wrong, it has been a while since I did this)

**Comment by DlbSt** [comment]
> @DlbSt Feel free to use those bits in an update to the docs. I think the demo code doesn't have it because of an update to newer PrismLib doesn't require it and I missed the update in the sample.. I think what I was doing in that blog post isn't needed if PrismLib is updated (I may be wrong, it has been a while since I did this)

I tested it on two devices (Win 10 Build 10.0.19041, Visual Studio 16.7, Prism.DryIoc.Forms 7.2.0.1422) and it was always necessary to edit .csproj file. If I don't modify the .csproj file, I am getting System.TypeLoadException.

**Comment by brianlagunas** [comment]
This has been open too long and this needs to be re-evaluated
