### ISSUE TITLE
Broken Link: Navigation

### ISSUE THREAD

**Issue by snehansh** [PrismLibrary/Prism-Documentation#79]
Documentation has broken link for Navigation within [View Composition-Navigation](https://prismlibrary.com/docs/wpf/view-composition.html#navigation) section. 
I have highlighted the link location in the attached snapshot.

![image](https://user-images.githubusercontent.com/35124383/90397465-810e4d80-e05d-11ea-823b-5c7168e506af.png)

**Comment by DerekFoulk** [comment]
Also, the documentation that it's supposed to link to is an empty MD file (save for the title). Not sure if this is related or not 😬

**Comment by brianlagunas** [comment]
We accept PRs

**Comment by DerekFoulk** [comment]
I would totally do so, but I'm trying to learn Prism still, hence why I discovered the missing doc.

**Comment by brianlagunas** [comment]
Fixing a link is a great frist PR contribution back to Prism.

**Comment by DerekFoulk** [comment]
@brianlagunas haha fair enough- I can do that much!
