### ISSUE TITLE
iOS Navigation bar with back button & maintain stack. 

### ISSUE THREAD

**Issue by bhaveshv007** [PrismLibrary/Prism-Documentation#82]
Hello Team,
I am using the Prism library in one of the Xamarin form project.
I follow steps given in video https://prismlibrary.com/docs/xamarin-forms/navigation/navigation-basics.html & it's working fine for Android but it's not giving me same behavior for iOS.
For Example
MainPage > Screen A > Screen B > Screen C
**Behavior  in Android**
Here in Android, each screen has a default back button at Navigation bar & If I press the back button from Screen C, It goes to Screen B & if I press the Back button from Screen B then it's going to Screen A. 

**Behavior in iOS**
Each screen has a default back button at Navigation bar & if I press the back button from Screen C, It navigates me to MainPage instead of Screen B.

I need the below kind of Behavior in my app for iOS.
Navigation Stack : MainPage > Screen A > Screen B > Screen C

>> MainPage & Screen A Should not have a navigation bar with a back button.
>> When I navigate to Screen B from Screen A, Screen B should have a Navigation bar with back button & title.
>> When I navigate to Screen C from Screen B, Screen C Should have also a back button with a title. 
>> Back button action should be the previous screen.

One More Scenario & behavior in iOS.
App.xmal.cs
>> MainPage opening by below Code.

        MainPage = new NavigationPage(new MainPage())
                {
               
                };
>> Screen A opening from MainPage from below code.

await navigationServ.NavigateAsync("ScreenA", null, false, true);

>> Screen B opening from Screen A from below Code.

await navigationService.NavigateAsync(new Uri("NavigationPage/ScreenB", UriKind.RelativeOrAbsolute));
![Screen B](https://user-images.githubusercontent.com/70191911/91154116-bb6f8e80-e6de-11ea-9955-ab44ae437b47.PNG)

>> Screen C opening from Screen B from below code.

await navigationService.NavigateAsync(new Uri("/ScreenC", UriKind.Relative));
![Screen C](https://user-images.githubusercontent.com/70191911/91154203-dcd07a80-e6de-11ea-9119-e19cc5c68205.PNG)

Not sure why it's giving 2 navigation bars at Screen C in place of a single one.

Can someone help me?

Thanks in Advance.

**Comment by brianlagunas** [comment]
This is not a documentation issue. You obviously have something wrong in your code, but since you did not share any code, there is no telling what your issue is. Also, we do not answer these types of questions on GitHub. You should post your question on StackOverflow for community support, or become a sponsor and be added to the private slack channel for help.
