### ISSUE TITLE
Make Prism Modularity Support clearer

### ISSUE THREAD

**Issue by dansiegel** [PrismLibrary/Prism-Documentation#84]
# Description

As reported, the current Prism Modularity docs make it seem that Modularity is supported for WPF & Uno, and it's less clear that it is supported for Xamarin.Forms. The docs need to be updated to make this abundantly clear. 

Since the API's are nearly identical the Modules topic should move from WPF to the core level

**Comment by MichaelPonti** [comment]
Happy Holidays @dansiegel , @brianlagunas!

It can be assigned to me if no one is working on it. I was going to take a swing at wpf navigation over the next week or so anyways.

**Comment by brianlagunas** [comment]
It's all your my friend.

**Comment by MichaelPonti** [comment]
PR #92
