### ISSUE TITLE
Doc Error - Link not working in Page "Dependency Injection with Prism"

### ISSUE THREAD

**Issue by SungracePrashant** [PrismLibrary/Prism-Documentation#99]
Hi,
I was reading Prism docs and found that link in below image is not working.

![image](https://user-images.githubusercontent.com/48211346/106270282-bdbcb280-6253-11eb-9a2b-105afd8ac725.png)

Please fix this link or remove it.

Thanks

**Comment by brianlagunas** [comment]
Can you create a PR to fix it?

**Comment by brianlagunas** [comment]
Actually, I just checked it and it works fine
